// This file was generated by counterfeiter
package prfakes

import (
	"sync"
	"time"

	"github.com/calebamiles/github-client/milestone"
	"github.com/calebamiles/github-client/prs/pr"
)

type FakeBasicPullRequest struct {
	IDStub        func() string
	iDMutex       sync.RWMutex
	iDArgsForCall []struct{}
	iDReturns     struct {
		result1 string
	}
	AuthorStub        func() string
	authorMutex       sync.RWMutex
	authorArgsForCall []struct{}
	authorReturns     struct {
		result1 string
	}
	BodyStub        func() string
	bodyMutex       sync.RWMutex
	bodyArgsForCall []struct{}
	bodyReturns     struct {
		result1 string
	}
	TitleStub        func() string
	titleMutex       sync.RWMutex
	titleArgsForCall []struct{}
	titleReturns     struct {
		result1 string
	}
	OpenStub        func() bool
	openMutex       sync.RWMutex
	openArgsForCall []struct{}
	openReturns     struct {
		result1 bool
	}
	MergedStub        func() bool
	mergedMutex       sync.RWMutex
	mergedArgsForCall []struct{}
	mergedReturns     struct {
		result1 bool
	}
	ReviewersStub        func() []string
	reviewersMutex       sync.RWMutex
	reviewersArgsForCall []struct{}
	reviewersReturns     struct {
		result1 []string
	}
	CreatedAtStub        func() time.Time
	createdAtMutex       sync.RWMutex
	createdAtArgsForCall []struct{}
	createdAtReturns     struct {
		result1 time.Time
	}
	UpdatedAtStub        func() time.Time
	updatedAtMutex       sync.RWMutex
	updatedAtArgsForCall []struct{}
	updatedAtReturns     struct {
		result1 time.Time
	}
	ClosedAtStub        func() time.Time
	closedAtMutex       sync.RWMutex
	closedAtArgsForCall []struct{}
	closedAtReturns     struct {
		result1 time.Time
	}
	MergedAtStub        func() time.Time
	mergedAtMutex       sync.RWMutex
	mergedAtArgsForCall []struct{}
	mergedAtReturns     struct {
		result1 time.Time
	}
	CommitsURLStub        func() string
	commitsURLMutex       sync.RWMutex
	commitsURLArgsForCall []struct{}
	commitsURLReturns     struct {
		result1 string
	}
	CommentsURLStub        func() string
	commentsURLMutex       sync.RWMutex
	commentsURLArgsForCall []struct{}
	commentsURLReturns     struct {
		result1 string
	}
	ReviewCommentsURLStub        func() string
	reviewCommentsURLMutex       sync.RWMutex
	reviewCommentsURLArgsForCall []struct{}
	reviewCommentsURLReturns     struct {
		result1 string
	}
	FileChangeURLStub        func() string
	fileChangeURLMutex       sync.RWMutex
	fileChangeURLArgsForCall []struct{}
	fileChangeURLReturns     struct {
		result1 string
	}
	MilestoneStub        func() milestone.Milestone
	milestoneMutex       sync.RWMutex
	milestoneArgsForCall []struct{}
	milestoneReturns     struct {
		result1 milestone.Milestone
	}
	StringStub        func() string
	stringMutex       sync.RWMutex
	stringArgsForCall []struct{}
	stringReturns     struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBasicPullRequest) ID() string {
	fake.iDMutex.Lock()
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct{}{})
	fake.recordInvocation("ID", []interface{}{})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub()
	} else {
		return fake.iDReturns.result1
	}
}

func (fake *FakeBasicPullRequest) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *FakeBasicPullRequest) IDReturns(result1 string) {
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) Author() string {
	fake.authorMutex.Lock()
	fake.authorArgsForCall = append(fake.authorArgsForCall, struct{}{})
	fake.recordInvocation("Author", []interface{}{})
	fake.authorMutex.Unlock()
	if fake.AuthorStub != nil {
		return fake.AuthorStub()
	} else {
		return fake.authorReturns.result1
	}
}

func (fake *FakeBasicPullRequest) AuthorCallCount() int {
	fake.authorMutex.RLock()
	defer fake.authorMutex.RUnlock()
	return len(fake.authorArgsForCall)
}

func (fake *FakeBasicPullRequest) AuthorReturns(result1 string) {
	fake.AuthorStub = nil
	fake.authorReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) Body() string {
	fake.bodyMutex.Lock()
	fake.bodyArgsForCall = append(fake.bodyArgsForCall, struct{}{})
	fake.recordInvocation("Body", []interface{}{})
	fake.bodyMutex.Unlock()
	if fake.BodyStub != nil {
		return fake.BodyStub()
	} else {
		return fake.bodyReturns.result1
	}
}

func (fake *FakeBasicPullRequest) BodyCallCount() int {
	fake.bodyMutex.RLock()
	defer fake.bodyMutex.RUnlock()
	return len(fake.bodyArgsForCall)
}

func (fake *FakeBasicPullRequest) BodyReturns(result1 string) {
	fake.BodyStub = nil
	fake.bodyReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) Title() string {
	fake.titleMutex.Lock()
	fake.titleArgsForCall = append(fake.titleArgsForCall, struct{}{})
	fake.recordInvocation("Title", []interface{}{})
	fake.titleMutex.Unlock()
	if fake.TitleStub != nil {
		return fake.TitleStub()
	} else {
		return fake.titleReturns.result1
	}
}

func (fake *FakeBasicPullRequest) TitleCallCount() int {
	fake.titleMutex.RLock()
	defer fake.titleMutex.RUnlock()
	return len(fake.titleArgsForCall)
}

func (fake *FakeBasicPullRequest) TitleReturns(result1 string) {
	fake.TitleStub = nil
	fake.titleReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) Open() bool {
	fake.openMutex.Lock()
	fake.openArgsForCall = append(fake.openArgsForCall, struct{}{})
	fake.recordInvocation("Open", []interface{}{})
	fake.openMutex.Unlock()
	if fake.OpenStub != nil {
		return fake.OpenStub()
	} else {
		return fake.openReturns.result1
	}
}

func (fake *FakeBasicPullRequest) OpenCallCount() int {
	fake.openMutex.RLock()
	defer fake.openMutex.RUnlock()
	return len(fake.openArgsForCall)
}

func (fake *FakeBasicPullRequest) OpenReturns(result1 bool) {
	fake.OpenStub = nil
	fake.openReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeBasicPullRequest) Merged() bool {
	fake.mergedMutex.Lock()
	fake.mergedArgsForCall = append(fake.mergedArgsForCall, struct{}{})
	fake.recordInvocation("Merged", []interface{}{})
	fake.mergedMutex.Unlock()
	if fake.MergedStub != nil {
		return fake.MergedStub()
	} else {
		return fake.mergedReturns.result1
	}
}

func (fake *FakeBasicPullRequest) MergedCallCount() int {
	fake.mergedMutex.RLock()
	defer fake.mergedMutex.RUnlock()
	return len(fake.mergedArgsForCall)
}

func (fake *FakeBasicPullRequest) MergedReturns(result1 bool) {
	fake.MergedStub = nil
	fake.mergedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeBasicPullRequest) Reviewers() []string {
	fake.reviewersMutex.Lock()
	fake.reviewersArgsForCall = append(fake.reviewersArgsForCall, struct{}{})
	fake.recordInvocation("Reviewers", []interface{}{})
	fake.reviewersMutex.Unlock()
	if fake.ReviewersStub != nil {
		return fake.ReviewersStub()
	} else {
		return fake.reviewersReturns.result1
	}
}

func (fake *FakeBasicPullRequest) ReviewersCallCount() int {
	fake.reviewersMutex.RLock()
	defer fake.reviewersMutex.RUnlock()
	return len(fake.reviewersArgsForCall)
}

func (fake *FakeBasicPullRequest) ReviewersReturns(result1 []string) {
	fake.ReviewersStub = nil
	fake.reviewersReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeBasicPullRequest) CreatedAt() time.Time {
	fake.createdAtMutex.Lock()
	fake.createdAtArgsForCall = append(fake.createdAtArgsForCall, struct{}{})
	fake.recordInvocation("CreatedAt", []interface{}{})
	fake.createdAtMutex.Unlock()
	if fake.CreatedAtStub != nil {
		return fake.CreatedAtStub()
	} else {
		return fake.createdAtReturns.result1
	}
}

func (fake *FakeBasicPullRequest) CreatedAtCallCount() int {
	fake.createdAtMutex.RLock()
	defer fake.createdAtMutex.RUnlock()
	return len(fake.createdAtArgsForCall)
}

func (fake *FakeBasicPullRequest) CreatedAtReturns(result1 time.Time) {
	fake.CreatedAtStub = nil
	fake.createdAtReturns = struct {
		result1 time.Time
	}{result1}
}

func (fake *FakeBasicPullRequest) UpdatedAt() time.Time {
	fake.updatedAtMutex.Lock()
	fake.updatedAtArgsForCall = append(fake.updatedAtArgsForCall, struct{}{})
	fake.recordInvocation("UpdatedAt", []interface{}{})
	fake.updatedAtMutex.Unlock()
	if fake.UpdatedAtStub != nil {
		return fake.UpdatedAtStub()
	} else {
		return fake.updatedAtReturns.result1
	}
}

func (fake *FakeBasicPullRequest) UpdatedAtCallCount() int {
	fake.updatedAtMutex.RLock()
	defer fake.updatedAtMutex.RUnlock()
	return len(fake.updatedAtArgsForCall)
}

func (fake *FakeBasicPullRequest) UpdatedAtReturns(result1 time.Time) {
	fake.UpdatedAtStub = nil
	fake.updatedAtReturns = struct {
		result1 time.Time
	}{result1}
}

func (fake *FakeBasicPullRequest) ClosedAt() time.Time {
	fake.closedAtMutex.Lock()
	fake.closedAtArgsForCall = append(fake.closedAtArgsForCall, struct{}{})
	fake.recordInvocation("ClosedAt", []interface{}{})
	fake.closedAtMutex.Unlock()
	if fake.ClosedAtStub != nil {
		return fake.ClosedAtStub()
	} else {
		return fake.closedAtReturns.result1
	}
}

func (fake *FakeBasicPullRequest) ClosedAtCallCount() int {
	fake.closedAtMutex.RLock()
	defer fake.closedAtMutex.RUnlock()
	return len(fake.closedAtArgsForCall)
}

func (fake *FakeBasicPullRequest) ClosedAtReturns(result1 time.Time) {
	fake.ClosedAtStub = nil
	fake.closedAtReturns = struct {
		result1 time.Time
	}{result1}
}

func (fake *FakeBasicPullRequest) MergedAt() time.Time {
	fake.mergedAtMutex.Lock()
	fake.mergedAtArgsForCall = append(fake.mergedAtArgsForCall, struct{}{})
	fake.recordInvocation("MergedAt", []interface{}{})
	fake.mergedAtMutex.Unlock()
	if fake.MergedAtStub != nil {
		return fake.MergedAtStub()
	} else {
		return fake.mergedAtReturns.result1
	}
}

func (fake *FakeBasicPullRequest) MergedAtCallCount() int {
	fake.mergedAtMutex.RLock()
	defer fake.mergedAtMutex.RUnlock()
	return len(fake.mergedAtArgsForCall)
}

func (fake *FakeBasicPullRequest) MergedAtReturns(result1 time.Time) {
	fake.MergedAtStub = nil
	fake.mergedAtReturns = struct {
		result1 time.Time
	}{result1}
}

func (fake *FakeBasicPullRequest) CommitsURL() string {
	fake.commitsURLMutex.Lock()
	fake.commitsURLArgsForCall = append(fake.commitsURLArgsForCall, struct{}{})
	fake.recordInvocation("CommitsURL", []interface{}{})
	fake.commitsURLMutex.Unlock()
	if fake.CommitsURLStub != nil {
		return fake.CommitsURLStub()
	} else {
		return fake.commitsURLReturns.result1
	}
}

func (fake *FakeBasicPullRequest) CommitsURLCallCount() int {
	fake.commitsURLMutex.RLock()
	defer fake.commitsURLMutex.RUnlock()
	return len(fake.commitsURLArgsForCall)
}

func (fake *FakeBasicPullRequest) CommitsURLReturns(result1 string) {
	fake.CommitsURLStub = nil
	fake.commitsURLReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) CommentsURL() string {
	fake.commentsURLMutex.Lock()
	fake.commentsURLArgsForCall = append(fake.commentsURLArgsForCall, struct{}{})
	fake.recordInvocation("CommentsURL", []interface{}{})
	fake.commentsURLMutex.Unlock()
	if fake.CommentsURLStub != nil {
		return fake.CommentsURLStub()
	} else {
		return fake.commentsURLReturns.result1
	}
}

func (fake *FakeBasicPullRequest) CommentsURLCallCount() int {
	fake.commentsURLMutex.RLock()
	defer fake.commentsURLMutex.RUnlock()
	return len(fake.commentsURLArgsForCall)
}

func (fake *FakeBasicPullRequest) CommentsURLReturns(result1 string) {
	fake.CommentsURLStub = nil
	fake.commentsURLReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) ReviewCommentsURL() string {
	fake.reviewCommentsURLMutex.Lock()
	fake.reviewCommentsURLArgsForCall = append(fake.reviewCommentsURLArgsForCall, struct{}{})
	fake.recordInvocation("ReviewCommentsURL", []interface{}{})
	fake.reviewCommentsURLMutex.Unlock()
	if fake.ReviewCommentsURLStub != nil {
		return fake.ReviewCommentsURLStub()
	} else {
		return fake.reviewCommentsURLReturns.result1
	}
}

func (fake *FakeBasicPullRequest) ReviewCommentsURLCallCount() int {
	fake.reviewCommentsURLMutex.RLock()
	defer fake.reviewCommentsURLMutex.RUnlock()
	return len(fake.reviewCommentsURLArgsForCall)
}

func (fake *FakeBasicPullRequest) ReviewCommentsURLReturns(result1 string) {
	fake.ReviewCommentsURLStub = nil
	fake.reviewCommentsURLReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) FileChangeURL() string {
	fake.fileChangeURLMutex.Lock()
	fake.fileChangeURLArgsForCall = append(fake.fileChangeURLArgsForCall, struct{}{})
	fake.recordInvocation("FileChangeURL", []interface{}{})
	fake.fileChangeURLMutex.Unlock()
	if fake.FileChangeURLStub != nil {
		return fake.FileChangeURLStub()
	} else {
		return fake.fileChangeURLReturns.result1
	}
}

func (fake *FakeBasicPullRequest) FileChangeURLCallCount() int {
	fake.fileChangeURLMutex.RLock()
	defer fake.fileChangeURLMutex.RUnlock()
	return len(fake.fileChangeURLArgsForCall)
}

func (fake *FakeBasicPullRequest) FileChangeURLReturns(result1 string) {
	fake.FileChangeURLStub = nil
	fake.fileChangeURLReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) Milestone() milestone.Milestone {
	fake.milestoneMutex.Lock()
	fake.milestoneArgsForCall = append(fake.milestoneArgsForCall, struct{}{})
	fake.recordInvocation("Milestone", []interface{}{})
	fake.milestoneMutex.Unlock()
	if fake.MilestoneStub != nil {
		return fake.MilestoneStub()
	} else {
		return fake.milestoneReturns.result1
	}
}

func (fake *FakeBasicPullRequest) MilestoneCallCount() int {
	fake.milestoneMutex.RLock()
	defer fake.milestoneMutex.RUnlock()
	return len(fake.milestoneArgsForCall)
}

func (fake *FakeBasicPullRequest) MilestoneReturns(result1 milestone.Milestone) {
	fake.MilestoneStub = nil
	fake.milestoneReturns = struct {
		result1 milestone.Milestone
	}{result1}
}

func (fake *FakeBasicPullRequest) String() string {
	fake.stringMutex.Lock()
	fake.stringArgsForCall = append(fake.stringArgsForCall, struct{}{})
	fake.recordInvocation("String", []interface{}{})
	fake.stringMutex.Unlock()
	if fake.StringStub != nil {
		return fake.StringStub()
	} else {
		return fake.stringReturns.result1
	}
}

func (fake *FakeBasicPullRequest) StringCallCount() int {
	fake.stringMutex.RLock()
	defer fake.stringMutex.RUnlock()
	return len(fake.stringArgsForCall)
}

func (fake *FakeBasicPullRequest) StringReturns(result1 string) {
	fake.StringStub = nil
	fake.stringReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBasicPullRequest) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.authorMutex.RLock()
	defer fake.authorMutex.RUnlock()
	fake.bodyMutex.RLock()
	defer fake.bodyMutex.RUnlock()
	fake.titleMutex.RLock()
	defer fake.titleMutex.RUnlock()
	fake.openMutex.RLock()
	defer fake.openMutex.RUnlock()
	fake.mergedMutex.RLock()
	defer fake.mergedMutex.RUnlock()
	fake.reviewersMutex.RLock()
	defer fake.reviewersMutex.RUnlock()
	fake.createdAtMutex.RLock()
	defer fake.createdAtMutex.RUnlock()
	fake.updatedAtMutex.RLock()
	defer fake.updatedAtMutex.RUnlock()
	fake.closedAtMutex.RLock()
	defer fake.closedAtMutex.RUnlock()
	fake.mergedAtMutex.RLock()
	defer fake.mergedAtMutex.RUnlock()
	fake.commitsURLMutex.RLock()
	defer fake.commitsURLMutex.RUnlock()
	fake.commentsURLMutex.RLock()
	defer fake.commentsURLMutex.RUnlock()
	fake.reviewCommentsURLMutex.RLock()
	defer fake.reviewCommentsURLMutex.RUnlock()
	fake.fileChangeURLMutex.RLock()
	defer fake.fileChangeURLMutex.RUnlock()
	fake.milestoneMutex.RLock()
	defer fake.milestoneMutex.RUnlock()
	fake.stringMutex.RLock()
	defer fake.stringMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeBasicPullRequest) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pr.BasicPullRequest = new(FakeBasicPullRequest)
